### ISSUE TITLE
Failed to start: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by anas10** [KEGustafsson/signalk-onvif-camera#4]
Hi,
when I install your plugin it does not appear in the plugin config tab for configuration like on your readme.
I only see this error on the dashboard view:
`Failed to start: The "path" argument must be of type string. Received undefined`
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/5764537/219938436-199dabe4-fb74-4475-a18c-ad984efd8b23.png">

And when I click to open the web app, it searches for ever and I have the following errors in the console:
<img width="1959" alt="image" src="https://user-images.githubusercontent.com/5764537/219938471-1cb8b34f-378c-4f06-80d7-0a3e39cb761a.png">
Is there a configuration step I am missing?

**Comment by KEGustafsson** [comment]
There should be following plugin config section, where you should be able to define LAN, protocol, credentials and camera details.

![Screenshot_20230219_124857_Firefox.jpg](https://user-images.githubusercontent.com/3332251/219943477-cb48e183-032e-40ad-b0f5-8c41fe846131.jpg)

Which version of SignalK you are using?

If I don't recall totally wrong, I modified search so that only listed cameras in the plugin are valid and if there is none, the this might cause the error. I need to check it.

Was there any problems or error during installation phase?

1) LAN is needed if you have several LANs. This points which LAN have the camera(s)

2) Server port is needed due to fact that we are running separate websocket server. Not related to SignalK

3) Credentials for ONVIF camera(s)

4) IP addresses for the camera(s)

If these parameters are not defined then error might happen. But if config part is not visible plugin configuration tab, that is a bit mystery?

**Comment by anas10** [comment]
Sorry for the late response, I missed your reply.

The version of SignalK I use is the one embedded with the cerbo VenusOS Large (version 1.44.0).

I cannot see the plugin section you are referring to. I can only see it in the webapps tab.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/5764537/226425808-89db28a6-b95d-4440-8fbc-89cc31c1fe50.png">

I've done a fresh install of the plugin. I don't see any issues during the installation phase. This is what I have in the logs, there is one error but I'm not sure it is related:
```
Mar 20 18:01:21 POST /skServer/appstore/install/signalk-onvif-camera/0.1.3 200 3866.560 ms - 34
Mar 20 18:01:23 GET /admin/270.js.map 200 245.683 ms - -
Mar 20 18:01:27 TypeError [ERR_INVALID_ARG_TYPE]: The "target" argument must be an instance of Buffer or Uint8Array. Received undefined at _copy (buffer.js:212:11) at Buffer.copy (buffer.js:768:12) at Parser._parse (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:175:26) at Parser.parsePgnData (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:320:24) at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:302:19) at CanboatJs._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:52:34) at CanboatJs.Transform._read (internal/streams/transform.js:205:10) at CanboatJs.Transform._write (internal/streams/transform.js:193:12) at writeOrBuffer (internal/streams/writable.js:358:12) at CanboatJs.Writable.write (internal/streams/writable.js:303:10) at CanbusStream.ondata (internal/streams/readable.js:726:22) at CanbusStream.emit (events.js:400:28) at addChunk (internal/streams/readable.js:290:12) at readableAddChunk (internal/streams/readable.js:265:9) at CanbusStream.Readable.push (internal/streams/readable.js:204:10) at CanbusStream.Transform.push (internal/streams/transform.js:166:32) { code: 'ERR_INVALID_ARG_TYPE' }
Mar 20 18:01:29 TcpProvider:connect EHOSTUNREACH 192.168.1.174:10110
```
Still the same issues after removing the plugin, restarting and installing again.
